from sqlalchemy.ext.asyncio import AsyncSession

from app.services.email import EmailService
from app.repositories.user import UserRepository
from app.models.user import User
from app.utils.security import hash_password, verify_password
from app.utils.email_verification import generate_verification_token, hash_verification_token, get_verification_expiry
from datetime import datetime, timezone
from app.utils.password_reset import get_password_reset_expiry, hash_password_reset_token, generate_password_reset_token


class UserService:

    def __init__(self,db : AsyncSession):
        self.db = db
        self.user_repository = UserRepository(db)
        self.email_service = EmailService()

    async def register_user(
            self,
            email: str,
            password : str,
            full_name : str,
    ):
        existing_user = await self.user_repository.get_by_email(email)

        if existing_user:
            # existing and already verified
            if existing_user.email_verified:
                raise ValueError("Email already registered")

            # existing but not verified
            verification_token = generate_verification_token()
            hashed_password = hash_password(password)

            existing_user.verification_token_hash = hash_verification_token(verification_token)
            existing_user.verification_token_expires_at = get_verification_expiry()
            existing_user.full_name = full_name
            existing_user.password_hash = hashed_password

            await self.db.commit()

            # send verification email
            await self.email_service.send_verification_email(
                email=email,
                verification_token=verification_token,
            )

            return existing_user

        # completely new user
        verification_token = generate_verification_token()
        verification_token_hash = hash_verification_token(verification_token)
        hashed_password = hash_password(password)
        verification_token_expiry = get_verification_expiry()

        user = await self.user_repository.create(
            email=email,
            hashed_password=hashed_password,
            full_name=full_name,
            verification_token_hash = verification_token_hash,
            verification_token_expiry_at = verification_token_expiry,
        )

        await self.db.commit() # transactions commited
        await self.db.refresh(user) # syncs python obj with DB values. useful for values generated by db itself.

        # send verification email
        await self.email_service.send_verification_email(
            email=email,
            verification_token=verification_token,
        )
        return user


    async def authenticate_user(
            self,
            email : str,
            password : str,
    ):
        user = await self.user_repository.get_by_email(email)

        if not user:
            raise ValueError("Invalid email or password")

        if not verify_password(password,user.password_hash):
            raise ValueError("Invalid email or password")

        if not user.email_verified:
            raise ValueError("Please verify your email before logging in")
        
        return user # User model class object


    async def update_user(
            self,
            full_name : str,
            user_data : User,
    ):
        user = await self.user_repository.update(
            full_name=full_name,
            user_data=user_data,
        )

        await self.db.commit()

        return user


    async def delete_user(
            self,
            user : User,
    ):
        user = await self.user_repository.delete(
            user = user,
        ) # type: ignore

        await self.db.commit()


    async def verify_email(
            self,
            token : str,
    ):

        token_hash = hash_verification_token(token)

        user = await self.user_repository.get_by_verification_token_hash(token_hash)

        if not user:
            raise ValueError("Invalid link")

        if ( user.verification_token_expires_at is None or user.verification_token_expires_at <= datetime.now(timezone.utc)):
            raise ValueError("Verification token has expired")

        user.email_verified = True
        user.verification_token_expires_at = None # invalidating the token
        user.verification_token_hash = None

        await self.db.commit()

        return user



    async def resend_verification_email(
            self,
            email : str,
    ):
        user = await self.user_repository.get_by_email(email)

        if not user:
            return

        if user.email_verified:
            return
        # both if will return the same message to avoid attacker to get any information

        verification_token = generate_verification_token()
        verification_token_hash = hash_verification_token(verification_token)
        verification_token_expiry = get_verification_expiry()

        user.verification_token_hash = verification_token_hash
        user.verification_token_expires_at = verification_token_expiry

        await self.db.commit()

        await self.email_service.send_verification_email(
            email=email,
            verification_token=verification_token,
        )


    async def forgot_password(
            self,
            email : str,
    ):

        user = await self.user_repository.get_by_email(email)

        if not user:
            return

        if not user.email_verified: # coz email membership must belong to user
            return

        reset_password_token = generate_password_reset_token()

        user.password_reset_token_hash = hash_password_reset_token(reset_password_token)
        user.password_reset_token_expires_at = get_password_reset_expiry()

        await self.db.commit()

        await self.email_service.send_password_reset_email(
            email = email,
            reset_token = reset_password_token,
        )


    async def reset_password(
            self,
            token : str,
            new_password : str,
    ):

        token_hash = hash_password_reset_token(token)

        user = await self.user_repository.get_by_password_reset_token_hash(
            token_hash
        )

        if not user:
            raise ValueError("Invalid link")

        if (
            user.password_reset_token_expires_at is None
            or user.password_reset_token_expires_at <= datetime.now(timezone.utc)
        ):
            raise ValueError("Password reset token has expired")

        user.password_hash = hash_password(new_password)

        user.password_reset_token_hash = None
        user.password_reset_token_expires_at = None

        await self.db.commit()

        return user