from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.user import UserRepository
from app.models.user import User
from app.utils.security import hash_password, verify_password
from app.utils.email_verification import generate_verification_token, hash_verification_token, get_verification_expiry
from datetime import datetime, timezone


class UserService:

    def __init__(self,db : AsyncSession):
        self.db = db
        self.user_repository = UserRepository(db)

    async def register_user(
            self,
            email: str,
            password : str,
            full_name : str,
    ):
        existing_user = await self.user_repository.get_by_email(email)

        if existing_user:
            # existing and already verified
            if existing_user.email_verified:
                raise ValueError("Email already registered")

            # existing but not verified
            verification_token = generate_verification_token()
            hashed_password = hash_password(password)

            existing_user.verification_token_hash = hash_verification_token(verification_token)
            existing_user.verification_token_expires_at = get_verification_expiry()
            existing_user.full_name = full_name
            existing_user.password_hash = hashed_password

            await self.db.commit()

            # later we will send verification_token through email
            return existing_user

        # completely new user
        verification_token = generate_verification_token()
        verification_token_hash = hash_verification_token(verification_token)
        hashed_password = hash_password(password)
        verification_token_expiry = get_verification_expiry()

        user = await self.user_repository.create(
            email=email,
            hashed_password=hashed_password,
            full_name=full_name,
            verification_token_hash = verification_token_hash,
            verification_token_expiry_at = verification_token_expiry,
        )

        await self.db.commit() # transactions commited
        await self.db.refresh(user) # syncs python obj with DB values. useful for values generated by db itself.
        # later we will send verification_token through email
        return user


    async def authenticate_user(
            self,
            email : str,
            password : str,
    ):
        user = await self.user_repository.get_by_email(email)

        if not user:
            return None

        if not verify_password(password,user.password_hash):
            return None

        return user # User model class object


    async def update_user(
            self,
            full_name : str,
            user_data : User,
    ):
        user = await self.user_repository.update(
            full_name=full_name,
            user_data=user_data,
        )

        await self.db.commit()

        return user


    async def delete_user(
            self,
            user : User,
    ):
        user = await self.user_repository.delete(
            user = user,
        ) # type: ignore

        await self.db.commit()


    async def verify_email(
            self,
            token : str,
    ):

        token_hash = hash_verification_token(token)

        user = await self.user_repository.get_by_verification_token_hash(token_hash)

        if not user:
            raise ValueError("Invalid link")

        if ( user.verification_token_expires_at is None or user.verification_token_expires_at <= datetime.now(timezone.utc)):
            raise ValueError("Verification token has expired")

        user.email_verified = True
        user.verification_token_expires_at = None # invalidating the token
        user.verification_token_hash = None

        await self.db.commit()

        return user
