from sqlalchemy.ext.asyncio import AsyncSession

from app.repositories.user import UserRepository
from app.models.user import User
from app.utils.security import hash_password, verify_password



class UserService:

    def __init__(self,db : AsyncSession):
        self.db = db
        self.user_repository = UserRepository(db)

    async def register_user(
            self,
            email: str,
            password : str,
            full_name : str,
    ):
        existing_user = await self.user_repository.get_by_email(email)

        if existing_user:
            raise ValueError("Email already registered")

        hashed_password = hash_password(password)

        user = await self.user_repository.create(
            email=email,
            hashed_password=hashed_password,
            full_name=full_name,
        )

        await self.db.commit() # transactions commited
        await self.db.refresh(user) # syncs python obj with DB values. useful for values generated by db itself.
        return user


    async def authenticate_user(
            self,
            email : str,
            password : str,
    ):
        user = await self.user_repository.get_by_email(email)

        if not user:
            return None

        if not verify_password(password,user.password_hash):
            return None

        return user # User model class object


    async def update_user(
            self,
            full_name : str,
            user_data : User,
    ):
        user = await self.user_repository.update(
            full_name=full_name,
            user_data=user_data,
        )

        await self.db.commit()

        return user
