"""add task version

Revision ID: 28e02629ae26
Revises: 6e82344575fb
Create Date: 2026-09-06 17:52:14.825663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e02629ae26'
down_revision: Union[str, Sequence[str], None] = '6e82344575fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('version', sa.Integer(), nullable=False,server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'version')
    # ### end Alembic commands ###
