"""add project version

Revision ID: a46a0425dadb
Revises: 28e02629ae26
Create Date: 2026-09-06 18:46:44.598461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a46a0425dadb'
down_revision: Union[str, Sequence[str], None] = '28e02629ae26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('version', sa.Integer(), nullable=False,server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'version')
    # ### end Alembic commands ###
