"""create comments invitation table now

Revision ID: c4850b55d157
Revises: 8cfa3fb5dc94
Create Date: 2026-09-04 19:57:44.565489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4850b55d157'
down_revision: Union[str, Sequence[str], None] = '8cfa3fb5dc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('invitations', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('invitations', 'expires_at')
    # ### end Alembic commands ###
