"""allow user deletion with historical references

Revision ID: ffa1c2101f19
Revises: a46a0425dadb
Create Date: 2026-09-14 19:43:49.572613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa1c2101f19'
down_revision: Union[str, Sequence[str], None] = 'a46a0425dadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Fix comments.user_id
    op.drop_constraint(
        op.f('comments_user_id_fkey'),
        'comments',
        type_='foreignkey'
    )

    op.alter_column(
        'comments',
        'user_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )

    op.create_foreign_key(
        None,
        'comments',
        'users',
        ['user_id'],
        ['id'],
        ondelete='SET NULL'
    )

    # Fix comments.task_id
    op.drop_constraint(
        op.f('comments_task_id_fkey'),
        'comments',
        type_='foreignkey'
    )

    op.create_foreign_key(
        None,
        'comments',
        'tasks',
        ['task_id'],
        ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey') # type: ignore
    op.drop_constraint(None, 'comments', type_='foreignkey') # type: ignore
    op.create_foreign_key(op.f('comments_task_id_fkey'), 'comments', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
